// Real Google Sheet data snapshot from 1VXIMchmEibTeO9nRIiXjMK518BhLzwOHsxqci5fX4LE
export const REAL_SHEET_HEADERS = [
  "ID",
  "Status",
  "name",
  "area",
  "zone",
  "اسم المشرف",
  "phone_number",
  "2026/09/28",
  "2026/09/29",
  "2026/09/30",
  "2026/10/01",
  "2026/10/02",
  "عدد الأيام المختاره"
];
export const REAL_SHEET_ROWS = [
  [
    "2112946",
    "Active",
    "Michael Jamal Habib Hanna _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1220130526",
    "غير مختار",
    "غير مختار",
    "مختار",
    "مختار",
    "مختار",
    "4"
  ],
  [
    "1205050",
    "Active",
    "Mosaad Adelmosaad Amin _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1277172656",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2261137",
    "Active",
    "Hani Wanis Saleh Abdemalak _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1211244310",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "غير مختار",
    "4"
  ],
  [
    "2420151",
    "Active",
    "Mohamed Mousa Abdelmalek Ahmed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1200435892",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2142863",
    "Active",
    "Ali Mohammed Ali Khafaji _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1141305610",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2097872",
    "Active",
    "Amein Shaban Amein Mahni _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1125612302",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2039256",
    "Active",
    "Omar Khaled Attia Abdallah _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1120156942",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2411638",
    "Active",
    "Basem Ramadan Soliman Maghawry _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1011477312",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2194656",
    "Active",
    "Ahmed Mahmoud Hadiya Mohammed _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1144258361",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2443888",
    "Active",
    "Ahmed Yehia Ahmed_EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1101026259",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2050600",
    "Active",
    "Hossam Sayed Mamdouh Wahba _ ELEZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1276072563",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2211521",
    "Active",
    "Mohamed Ramadan Mahmoud_EL Ezz",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1211871264",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "1167967",
    "Active",
    "Ali Fawzy Ali Abdelhamid _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1150644460",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2218401",
    "Active",
    "Hedya Mahmoud Hedya Mohamed _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1093814813",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2169188",
    "Active",
    "Mostafa Kamal Ali Mohamed _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1091673864",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "5"
  ],
  [
    "1282138",
    "Active",
    "Alaa Shaaban Mahmoud Ahmed _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1066454254",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2253259",
    "Active",
    "Mohamed Ibrahim Mohamed Ibrahim _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1064738947",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2370947",
    "Active",
    "Amr Mubarak Taha Shokry _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1027341836",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2371538",
    "Active",
    "Mohamed Zakria Ahmed Jebril _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1009043384",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2028547",
    "Active",
    "Ahmed Mohamed Abdelmageed Abdellatif _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1007818462",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2523607",
    "Active",
    "Salah Ahmed Salaheldien Saad _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1122146314",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3508768",
    "Active",
    "Sayed Ramadan Abdulaal Ibrahim _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1127932953",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3784204",
    "Active",
    "Mahmoud Sayed Yousef Riyad _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1095233469",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3815599",
    "Active",
    "Ali Ibrahim Ali Abdelhamid _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1112133482",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3836890",
    "Active",
    "Mohammed Amer Naeem Juma _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1280193652",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3862986",
    "Active",
    "Farid Sayed Farid Sayed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1289299214",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4044197",
    "Active",
    "Yusuf Muhammad Muhammad Ismail _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1018544052",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "غير مختار",
    "5"
  ],
  [
    "1556449",
    "Active",
    "Youssef Mabrok Ali Soliman _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1212147283",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "6"
  ],
  [
    "1568512",
    "Active",
    "Harbi Ramadan Ragab Ahmed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1200381795",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3783287",
    "Active",
    "Fadlallah Sameh Sharaf Hassan _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1125279959",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3784125",
    "Active",
    "Ziad Muhammad Jamal Abdelmalek _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1204428641",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4179600",
    "Active",
    "Mohamed Sherif Adly Ebrahim _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1210197285",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4246613",
    "Active",
    "Mohamed Yahya Abdelhamid Sayed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1279704229",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "مختار",
    "6"
  ],
  [
    "3850592",
    "Active",
    "Karim Ahmed Lotfy Metwally _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1099170808",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4245383",
    "Active",
    "Abdulrahman Salah Rizq Riziq _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1149377627",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4253023",
    "Active",
    "Mustafa Khalaf Mustafa Abdelghani _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1039343955",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4284486",
    "Active",
    "Yehya Elsayed Abdelmniem Elsayed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1025027742",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4339436",
    "Active",
    "Mohammed Mohammed Ali Mahmoud _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1558094636",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4450127",
    "Active",
    "Souhaib Ahmed Elsayed Saad _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1146836046",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4559526",
    "Active",
    "Mahmoud Mayhob Saeed Abdelhamid _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1281687679",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4564938",
    "Active",
    "Ahmed Mohamed Ahmed Lamloum     _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1029409731",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4580979",
    "Active",
    "Mohamed Kasban Bah Kamel _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1274982349",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4594470",
    "Active",
    "Hamdi Abdelaziz Ali Ahmed _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1090109724",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4595835",
    "Active",
    "Mustafa Sobhi Mohamed Khedr _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1220507629",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4614753",
    "Active",
    "Taher Khaled Elsayed Ali _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1555114665",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4614798",
    "Active",
    "Abdelrahman Hamido Mastour Azab _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1150346488",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4665795",
    "Active",
    "Ahmed Alhussieni Ahmed Abdulmaged _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1124602278",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4666657",
    "Active",
    "Youssef Adel Zaki Shehata _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1207282588",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4685635",
    "Active",
    "Abdelrahman Ali Abdelrahman Elsayed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1158106909",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4694142",
    "Active",
    "Omar Safi Salaheldin Abdelqawi _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1102764298",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4699302",
    "Active",
    "Ehab Taha Talaat Ibrahim _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1025492118",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4703395",
    "Active",
    "Abdullah Khaled Mahmoud Ahmed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1142330700",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4704957",
    "Active",
    "Mohamed Ahmed Ebrahim Ahmed _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1060296244",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4718792",
    "Active",
    "Mustafa Ashraf Shawqy Sayed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1055195551",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4726388",
    "Active",
    "Mohammed Najib Rashd Aliyu _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1129547236",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4739012",
    "Active",
    "Mahmoud Gaber Shaker Awad  _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1028937609",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4765701",
    "Active",
    "Mahmoud Hatem Mohamed Youssef _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1118036164",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4772184",
    "Active",
    "Mohamed Ashraf Shawky Sayed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1032753821",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4775560",
    "Active",
    "Hussein Elsayed Hassan Hussein _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1143251559",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4801228",
    "Active",
    "Ziad Ayman Khalaf Hamed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1067508960",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4820161",
    "Active",
    "Karim Osama Mansour Abdelhamid _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1214836321",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4832738",
    "Active",
    "Omar Ali Mohammad Ali _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1143633673",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4839416",
    "Active",
    "Zaki Rifai Zaki Mohamed _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1124701706",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4907394",
    "Active",
    "Mohamed Khairy Abdelhakiem Hammam _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1140357903",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4926064",
    "Active",
    "Ismail Abdelaal Ismail Abdelaal _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1128122985",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "4772231",
    "Active",
    "Alaa Saber Mustafa Qarni _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1032553912",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "3991446",
    "Active",
    "Muhammad Gadalmawla Sayed Abdelhamid _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1149852241",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2173341",
    "Active",
    "Ahmad Abdelzaher Hassan Hussien _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1224001876",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2252945",
    "Active",
    "Abdelsattar Ahmed Abdelsattar_EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1152657090",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2129623",
    "Active",
    "Abdulrahman Alzare Muhammad Ibrahim _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1280846415",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "613995",
    "Active",
    "Feliopater Adel Maken _EL EZZ",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1284372976",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ],
  [
    "2607259",
    "Active",
    "Ziad Ayman Ali Ismail _EL EZZ_BC",
    "Masre Elgdeda",
    "Hiliopolise",
    "كريم شعبان محمود احمد",
    "1029228814",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "غير مختار",
    "0"
  ]
];
